# all paths are relative to the project root
paths:
  data:
    dalip_stackoverflow_dataset: "data/dalip_stackoverflow_dataset/dalip_stackoverflow_dataset.csv"
    dalip_hf_dataset: "data/dalip_hf_dataset/"
    dalip_stackoverflow_mv_feat_mv_results: "data/dalip_stackoverflow_results/MV_FEAT_MV_results_stack.txt"
    dalip_stackoverflow_mv_results: "data/dalip_stackoverflow_results/MV_results_stack.txt"

  models:
    dalip_embeddings_test: "models/dalip/embeddings/test/"
    dalip_embeddings: "models/dalip/embeddings/"
    dalip_bi-encoder: "models/dalip/bi-encoder/"
    dalip_cross-encoder: "models/dalip/cross-encoder"
    dalip_bi-encoder_ranking: "models/dalip/bi-encoder_ranking"
    dalip_cross-encoder_ranking: "models/dalip/cross-encoder_ranking"